meta:
  schema-version: 0.1.0
  created-on: "2024-02-15T11:42:35Z"
  cli-version: 0.2.0
projects:
  2lambda123-gildedrose-refactoring-kata-js-jest-package-lock.json:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "5"
    overrides:
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      semver:
        6.3.0:
          use: 6.3.0-sp1
        5.7.1:
          use: 5.7.1-sp1
      tough-cookie:
        2.5.0:
          use: 2.5.0-sp1
